# WITH RECURSIVE https://im-codding.tistory.com/82
WITH RECURSIVE GEN_DATA AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL # 조상
    UNION ALL
    SELECT E.ID, E.PARENT_ID, (GEN + 1) AS GEN
    FROM ECOLI_DATA E
    INNER JOIN GEN_DATA G ON E.PARENT_ID = G.ID
)
SELECT ID
FROM GEN_DATA
WHERE GEN = 3
ORDER BY ID ASC
;


# SELECT C.ID
# FROM ECOLI_DATA C
# INNER JOIN (
#     SELECT C.ID, P.PARENT_ID
#     FROM ECOLI_DATA P
#     INNER JOIN ECOLI_DATA C
#     ON P.ID = C.PARENT_ID
#     AND P.PARENT_ID IS NULL # 조상 찾기
# ) P
# ON P.ID = C.PARENT_ID
# ORDER BY ID ASC
# ;
