WITH RECURSIVE GEN_DATA AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, (GEN + 1) AS GEN
    FROM ECOLI_DATA E
    INNER JOIN GEN_DATA G ON E.PARENT_ID = G.ID
)

SELECT COUNT(GEN) AS COUNT, GEN AS GENERATION
FROM GEN_DATA
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GEN
ORDER BY GEN
;
