-- 트럭 대여 금액 구하기
-- 대여 기록 ID, 대여 금액 리스트
-- 대여 금액 내림차순, 대여 기록 ID 내림차순

-- 1. 대여기간에 따른 할인타입 구하기
-- 2. 기간별 할인 퍼센트 구하기
-- DATE 비교는 DATEDIFF 사용
-- LEFT JOIN을 이용해서 DURATION_TYPE이 NULL인 경우 구하기
-- JOIN때 AND와 WHERE 순서 차이 조심 ~!

WITH HISTORY AS (
    -- DATEDIFF로 대여기간 계산
    SELECT HISTORY_ID, DAILY_FEE, DATEDIFF(END_DATE,START_DATE) + 1 AS DURATION, START_DATE, END_DATE,
        (CASE WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE) + 1 >= 7 THEN '7일 이상'
        END) AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS B
    ON A.CAR_ID = B.CAR_ID
    AND B.CAR_TYPE = '트럭'
)
SELECT HISTORY_ID,
    (CASE WHEN HISTORY.DURATION_TYPE = '7일 이상' THEN ROUND(DAILY_FEE * DURATION * (100 - PLAN.DISCOUNT_RATE) / 100, 0) 
         WHEN HISTORY.DURATION_TYPE = '30일 이상' THEN ROUND(DAILY_FEE * DURATION * (100 - PLAN.DISCOUNT_RATE) / 100, 0) 
         WHEN HISTORY.DURATION_TYPE = '90일 이상' THEN ROUND(DAILY_FEE * DURATION * (100 - PLAN.DISCOUNT_RATE) / 100, 0)
     ELSE DAILY_FEE * DURATION
     END) AS FEE
FROM HISTORY
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN -- LEFT JOIN을 해야 7일 미만의 경우 NULL값이 나옴
ON HISTORY.DURATION_TYPE = PLAN.DURATION_TYPE
AND PLAN.CAR_TYPE = '트럭' -- AND 써야됨 !! ON ~ AND(조인 전), WHERE(조인 후) ... INNER를 쓰는 경우는 상관없지만 OUTER를 하는 경우 주의 !!!
-- AND의 경우, HISTORY.DURAION_TYPE = NULL인 경우가 남아있음
-- WHERE의 경우, PLAN.CAR_TYPE = '트럭'인 행에는 DURATION_TYPE = NULL인 행이 없으므로 DURATION_TYPE = NULL인 행 제거 
ORDER BY FEE DESC, HISTORY_ID DESC;
