-- 코드를 작성해주세요
WITH PERCENTAGE AS (
    SELECT ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_GROUP
    FROM ECOLI_DATA
),
COLONY_NAMES AS (
    SELECT ID,
        CASE SIZE_GROUP
            WHEN 1 THEN 'CRITICAL'
            WHEN 2 THEN 'HIGH'
            WHEN 3 THEN 'MEDIUM'
            WHEN 4 THEN 'LOW'
        END AS COLONY_NAME
    FROM PERCENTAGE
)

SELECT E.ID, C.COLONY_NAME
FROM ECOLI_DATA E
JOIN COLONY_NAMES C
ON E.ID = C.ID
ORDER BY E.ID
;
